services:
  firmware-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firmware
    stdin_open: true
    tty: true
    volumes:
      - ./volumes:/home/builder/firmware-build
    environment:
      - firmware_DIR=/home/builder/firmware-build
    user: "builder"
    networks:
      - firmware-net

networks:
  firmware-net:
    driver: bridge
